steps:
  - id: 'npm_install'
    name: node
    entrypoint: npm
    args: ['install']
  - id: 'generate_dist'
    name: node
    entrypoint: npm
    args: ['run', 'generate:$_ENV_MODE']
  - id: 'move_dist_to_storage'
    name: gcr.io/cloud-builders/gsutil
    args: ['-m', 'rsync', '-r', '-c', '-d', './dist', 'gs://v2.tumwebsme.com']
